#  Maximum Likelihood - Linear Model


## Authors
Damien Ségransan

## Learning Goals
Use the formalism seen in Class to compute the Maximum Likelihood estimate of a linear model:
1. the variance/covariance matrix of the model parameters
2. the model parameters and their uncertainties
3. the correlations between the model parameters


## Keywords
Maximum Likelihood, $\chi^2$, Linear Model



## Context
### Experimental data
Let's consider an experiment where a set of N measurements $y_i$ are recorded at time $t_i$. For each measurement $y_i$, an error $ey_i$ has been  estimated. We assume here that the experimental setup is such that the measurement $y_i$ can be considered as drawn from a Normal distribution with independant random variables (Gaussian White Noise) where $ey_i$ is an good estimate of the standard deviation of such distributions.

The datasets that you will read form the ascii file *dataFile.csv* consists of a set of 3 vectors : 

$$
\begin{align*}
\boldsymbol{t}=\begin{bmatrix} t_0\\
t_1\\
 \vdots\\
t_{N-1}\end{bmatrix}, \,\,\boldsymbol{y}=\begin{bmatrix} y_0\\
y_1\\
 \vdots\\
y_{N-1}\end{bmatrix}, \,\,\boldsymbol{ey}=\begin{bmatrix} ey_0\\
ey_1\\
 \vdots\\
ey_{N-1}\end{bmatrix}
 \end{align*}$$



### Modeling the data
You will model the experimental data using the following linear model : 
$f(t_i;\boldsymbol{a}) = a_0 + a_1\,t + a_2 \, \cos{\Big(\frac{2 \pi \,t_i}{P}\Big)}+a_3 \, \sin{\Big(\frac{2 \pi \, t_i}{P}\Big)}$
where  $P=3.2$ is the period of the signal and $\boldsymbol{a} =\begin{bmatrix} a_0\\
a_1\\
a_2\\
a_3\\
\end{bmatrix}
$ are the model parameters (to be estimated)<br>

Let's simplify the notation such that $f_i = f_i(\boldsymbol{a}) = f(t_i|\boldsymbol{a})$ and further simplify the notation to:<br>
$
\boldsymbol{f}=\begin{bmatrix} f_0\\
f_1\\
 \vdots\\
f_{N-1}\end{bmatrix}
$

The linear model can be written as 

$$
\begin{align*}
\begin{bmatrix} f_0\\
f_1\\
 \vdots\\
f_{N-1}\end{bmatrix} = \begin{bmatrix} 
1  & t_{0}&\cos{\Big(\frac{2 \pi \,t_0}{P}\Big)} & \sin{\Big(\frac{2 \pi \,t_0}{P}\Big)}\\
1  & t_{1}&\cos{\Big(\frac{2 \pi \,t_1}{P}\Big)} &  \sin{\Big(\frac{2 \pi \,t_1}{P}\Big)}\\
 \vdots  & \vdots&  \vdots &  \vdots\\
1. &  t_{N-1}&\cos{\Big(\frac{2 \pi \,t_{N-1}}{P}\Big)} &  \sin{\Big(\frac{2 \pi \,t_{N-1}}{P}\Big)}
\end{bmatrix}.\begin{bmatrix} a_0\\
a_1\\
a_2\\
a_3
\end{bmatrix}
 \end{align*}$$

or as $$\boldsymbol{f} = \boldsymbol{X} . \boldsymbol{a} $$


where $\boldsymbol{X}$ is the **basis matrix**.



### Question 1) Read the data stored in the file *dataFile.csv* 

In [2]:
import astropy.io.ascii as ascii
import Functions as AC
import numpy as np
import matplotlib.pyplot as plt
#do it yourself


data = AC.data_loader("dataFile.csv")
print(data)
N=len(data['t'])
print(N)
t = np.array(data['t'])[:,np.newaxis] 
y = np.array(data['y'])
ey = np.array(data['ey']) 



            t          y        ey
0    0.228271  10.332252  1.001974
1    0.971738 -11.709249  1.256096
2    1.860219  -4.655806  1.406310
3    2.178692   8.047363  1.306263
4    2.472763  15.164463  1.360878
5    5.483577  10.177736  1.145938
6    6.970131   1.889571  1.458887
7    7.538958 -10.356763  1.357288
8    8.236843  -6.024950  1.271272
9    8.365838  -1.240522  1.071085
10   8.484527   1.559459  1.186670
11  10.487327  -8.332717  1.337067
12


### Question 2)  Maximum Likelihood estimate of the Covariance Matrix $\boldsymbol C_{\hat{a}}$ of $\boldsymbol a$



In [3]:
#Build the Basis Matrix. 

#Advice : Always check the shape of your matrix using np.shape()
# You'll be using np.vstack, np.transpose. 
P=3.2

theta=2*np.pi*data['t']/P

ones = np.ones((N,1))

cos = np.cos(2*(np.pi)*t/(P))
    
Cos = np.array(cos)



sin = np.sin(2*(np.pi)*t/(P))


Sin = np.array(sin)
print(Sin)


basis_matrix = np.hstack((ones,t,Cos,Sin))


print(basis_matrix)

[[ 0.43335219]
 [ 0.94368249]
 [-0.48899637]
 [-0.90706496]
 [-0.98981146]
 [-0.97398551]
 [ 0.89986051]
 [ 0.78658193]
 [-0.44845868]
 [-0.65812164]
 [-0.81420964]
 [ 0.98533566]]
[[ 1.          0.228271    0.90122465  0.43335219]
 [ 1.          0.971738   -0.33085247  0.94368249]
 [ 1.          1.860219   -0.87228582 -0.48899637]
 [ 1.          2.178692   -0.42099069 -0.90706496]
 [ 1.          2.472763    0.14238427 -0.98981146]
 [ 1.          5.483577   -0.2266103  -0.97398551]
 [ 1.          6.970131    0.43617779  0.89986051]
 [ 1.          7.538958   -0.61748593  0.78658193]
 [ 1.          8.236843   -0.89380356 -0.44845868]
 [ 1.          8.365838   -0.75291162 -0.65812164]
 [ 1.          8.484527   -0.58057098 -0.81420964]
 [ 1.         10.487327   -0.1706272   0.98533566]]


In [12]:
#Sigma is the covariance matrix of the data. 
#you'll be using np.diag, np.linalg.inv
Sigma=np.diag(ey**2)#fill the code here
print(Sigma.shape)

# print(Sigma)

#Weight of the data is the inverse of the covariance Sigma.
Weight=np.linalg.inv(Sigma)#fill the code here
print(Weight.shape)

print(basis_matrix.T.shape)


#compute the Covariance Matrix using np.matmul (or the @ operator), np.linalg.inv
Ca=np.linalg.inv((basis_matrix.T)@(Weight)@(basis_matrix)) #fill the code here

#What is the dimension of the covariance matrix ?
print(Ca.shape)

(12, 12)
(12, 12)
(4, 12)
(4, 4)


### Question 3)  $\boldsymbol{\hat{a}}$ : Maximum Likelihood estimate of $\boldsymbol{a}$ and corresponding uncertainties

In [17]:
#Use the Solution to the Normal Equation to estomate aMLE

#compute the Maximum Likelihood estimate of aMLE using np.linalg.solve, A, and b
aMLE=(np.linalg.inv(basis_matrix.T@Weight@basis_matrix))@basis_matrix.T@Weight@y #fill the code here
#compute the uncertainties on a using the Covariance matrix C of aMLE
aStd=np.diag(Ca) #fill the code here

print(aMLE)

print(aStd)


[ 2.92661494  0.05147235 13.84442476 -9.57220812]
[0.44203256 0.01502445 0.66157021 0.25856879]


### Question 4)  Compute and Display the correlation matrix of $\hat{a}$,*ie.* $R_{\hat{a}}$ where $R_{\hat{a},ij} = \frac{C_{\hat{a},ij}}{\sigma_i \, \sigma_j}$


In [ ]:
Raij = Ca/aStd



[[ 1.         -4.38307599 -0.20069075  0.20299157]
 [-0.14897838  1.          0.08035847 -0.04544641]
 [-0.3003648   3.53841752  1.         -0.66864455]
 [ 0.11874077 -0.7821268  -0.26133374  1.        ]]


: 

###  Question 5) Computation of the signal amplitude K and its uncertainity 



Let's consider function of a vector of random variables, $F(\boldsymbol a)$. Variations in the random vector $\boldsymbol a$, will results in variation in F. Provided that variations in 
variations in $\boldsymbol a$ are small, we can Taylor expand F to first-order and derive - and after some computation - derive the expression for the variance of F.<br>
$$\sigma^2_F = \Big(\frac{\partial F}{\partial a}\Big) \, C_a\,  \Big(\frac{\partial F}{\partial a}\Big)^T$$

Here $k=F(\boldsymbol a)=\sqrt{a_1^2 + a_2^2}$ 

In [ ]:
kMLE=  #fill the code here
dfda =  #fill the code here
kVar =  #fill the code here
kStd=  np.sqrt(kVar)
#print(kMLE,kVar, kStd)

###  Question 6) Maximum Likelihood estimate of the model :  $\boldsymbol{\hat{y}}$ and the corresponding predictive covariance Matrix. Is $\boldsymbol \Sigma_p$ diagonal?

In [ ]:
#Compute yMLE and its covariance Matrix at the time of the measurements. you may use np.diag




###  Question 7) Minimum $\chi^2$ 

In [ ]:
#Compute the $\chi^2$ corresponding to the aMLE

###  Question 8) Compute  $\boldsymbol{\hat{y}_c}$  and the corresponding predictive covariance Matrix for a continuous time vector $t_i = i \delta t$ with $i=0..101$ and $\delta t=0.15$. Is $\boldsymbol \Sigma_{c,p}$ diagonal?

In [ ]:
#You'll need to build a new basis matrix Xs with the new t vector generate a smooth model.
#use, np.linspace,  np.vstack etc... 

###  Question 9) Display the data (y vs. t) with errors. Overplot the $\boldsymbol{\hat{y}_c}$ with the $\pm 1\sigma$ confidence intervals 

In [ ]:
#You'll make use of matplotlib, and more specifically 
#fig, ax = plt.subplots(1,1, figsize=(20, 12))
#ax.plot
#ax.errorbar
#ax.fill_between